[package]
name = "quilt_builder"
version = "0.1.0"
authors = ["Coleman Sandefur <coleman.sandefur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.2"
gio = "0.9.1"
glib = "0.10.3"
cairo-rs = "0.9.1"
gdk = "0.13.0"
chrono = "0.4"
gdk-pixbuf = "0.9"
gdk-pixbuf-sys = "0.10"
gdk-sys = "0.10"
