[package]
name = "quilt_builder"
version = "0.1.0"
authors = ["Coleman Sandefur <coleman.sandefur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
yaml-rust = "0.4.5"
linked-hash-map = "0.5.4"
base64 = "0.13.0"
sha2 = "0.9.5"

chrono = "0.4"
gtk = "0.14.0"
gio = "0.14.0"
glib = "0.14.0"
cairo-rs = {version = "0.14.0", features = ["v1_16"]}
cairo-sys-rs = "0.14.0"
gdk = "0.14.0"
gdk-pixbuf = "0.14.0"
gdk-pixbuf-sys = "0.14.0"
gdk-sys = "0.14.0"